services:
  folochrome:
    depends_on:
      - postgres
    container_name: folochrome
    build:
      context: .
      dockerfile: config/docker/Dockerfile_Python
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000

    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    container_name: postgres
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=todolist

  adminer:
    depends_on:
      - postgres
    container_name: adminer
    image: adminer:latest
    ports:
      - 8080:8080

volumes:
  postgres_data:
